version: '3.3'

services:
  app:
    container_name: sample_web_app
    build: ./docker/app
    volumes:
    - ./www:/var/www
    networks:
      web_segment:
        ipv4_address: 172.250.0.2

  gw:
    image: nginx
    container_name: sample_web_gw
    ports:
    - 480:80
    volumes:
    - ./www:/var/www
    - ./docker/gw/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app
    networks:
      web_segment:
        ipv4_address: 172.250.0.3

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "33306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: uytsh87syJa
      MYSQL_USER: administrator
      MYSQL_PASSWORD: uytsh87syJa
      MYSQL_DATABASE: default_database
      TZ: "Asia/Tokyo"
    networks:
      web_segment:
        ipv4_address: 172.250.0.4

networks:
  web_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 172.250.0.0/24

volumes:
  db-store: